### ISSUE TITLE
Valid Ical feed url with no events has not been handled

### ISSUE THREAD

**Issue by sakshityagi** [manoj-nama/ical-parser#1]
Gives error :  `console.info("iCAL-PARSER:", objArr[0].VEVENT.length, "events parsed");
                                                     ^
TypeError: Cannot read property 'length' of undefined`

**Comment by manoj-nama** [comment]
Thanks @sakshityagi seems like an easy one to fix.

**Comment by manoj-nama** [comment]
@sakshityagi  Deployed a fix, let me know if that works for you.

**Comment by sakshityagi** [comment]
@manoj-nama Yes it worked. Thanks!
