### ISSUE TITLE
Event description gets truncated in response 

### ISSUE THREAD

**Issue by sakshityagi** [manoj-nama/ical-parser#2]
When I open the ical file, In see complete description but when I try to show the description from the response of the parser, it shows truncated text. 

This is kind of urgent. Looking forward for your reply :)

**Comment by manoj-nama** [comment]
@sakshityagi I've published the updated code to `npm`. Can you try if this works for you.

**Comment by sakshityagi** [comment]
@manoj-nama Worked for me. Thanks. :+1:
